#! /bin/sh

#
# BSPWM Sample file by D.Sánchez 2023
# Location: .config/bspwm/bspwmrc
#


pgrep -x sxhkd > /dev/null || sxhkd &

# Staring various programs

nitrogen --restore &
picom &
ulauncher --hide-window &
polybar -c ~/.config/polybar/config.ini &


# Configure window manager

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

#Sample ICONS             󰧚 󰢩 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Configure rules

bspc rule -a firefox desktop='^1'
bspc rule -a Terminator desktop='^2'
bspc rule -a telegram-desktop desktop='^10' state=floating follow=on
